name: Assign random reviewers
description: GitHub action for picking random reviewer from a GitHub team, written in Ruby.
inputs:
  github_access_token:
    description: Access token for reading a team list (must have `orgs:read` permission)
  organization_name:
    description: Name of the GitHub organization which the team belongs to
  team_name:
    description: Name of the team that their member should be picked as a reviewer
  number_of_reviewers:
    description: Number of reviewers we should pick
    default: 3
  only_available:
    description: Make this action only pick reviewers who do not have their status set to busy
    default: true
outputs:
  reviewers:
    description: A JSON array containing a list of GitHub usernames that are picked
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.github_access_token }}
    - ${{ inputs.organization_name }}
    - ${{ inputs.team_name }}
    - ${{ inputs.number_of_reviewers }}
    - ${{ inputs.only_available }}
